services:
  mcore-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcore-site
    restart: unless-stopped
    networks:
      - mcore
      - nginx

networks:
  mcore:
    name: mcore-site
  nginx:
    name: nginx
    external: true
